# Site settings
title: Avalia Stories
header-img: img/home-bg.jpg
email: miguel@avalia.systems
description: "Stories written by Avalia"
baseurl: "/Stories"
url: "https://avaliasystems.github.io"
github_username:  AvaliaSystems

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
