# Site settings
title: Avalia Stories
header-img: img/home-bg.jpg
email: miguel@avalia.systems
copyright_name: Your/Project/Corporate Name
description: "Stories written by Avalia"
baseurl: ""
url: "http://www.avalia.io/Stories/"
github_username:  AvaliaSystems

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
destination: public/_site
source: src
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
